version: '3.8'

services:
  db:
    image: postgres:13
    container_name: api_dgtn_db
    environment:
      POSTGRES_DB: dgtn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dgtn@2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api_network

  web:
    build: .
    container_name: api_dgtn_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:dgtn@2025@db:5432/dgtn
    networks:
      - api_network

  nginx:
    image: nginx:alpine
    container_name: api_dgtn_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - api_network

volumes:
  postgres_data:
  media_volume:
  static_volume:

networks:
  api_network:
    driver: bridge