# Generated by Django 4.2.24 on 2025-09-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
    ]
